openapi: 3.0.0
info:
  title: "liconic_telemetria"
  description: 'API para a plataforma de telemetria/gestão de créditos de carbono da Liconic'
  version: "1.0.0"
servers:
  - description:
    url: https://taflgn4sai.execute-api.us-east-2.amazonaws.com/dev
paths:
  /geradores:
    get:
      tags:
        - /geradores
      summary: "Lista os geradores (macaddresses)"

      responses:
        "200":
          description: "200 response"
          content:
            application/json: {}
      security:
        - CognitoAuth: []

  /dados:
    get:
      tags:
        - /dados
      summary: "Para consumir os dados é necessário informar o mac, datainicio e datafim."
      parameters:
        - name: mac
          in: query
          required: false
          schema:
            type: string
          example: "12-34-56-78-9A-BC"
        - name: datainicio
          in: query
          required: false
          schema:
            type: string
          example: "01-04-2024"
        - name: datafim
          in: query
          required: false
          schema:
            type: string
          example: "08-04-2024"
      responses:
        "200":
          description: "200 response"
          content:
            application/json: {}
      security:
        - CognitoAuth: []
        
  /clientes:
    get:
      tags:
        - /clientes
      summary: "Lista os clientes e as suas informações"

      responses:
        "200":
          description: "200 response"
          content:
            application/json: {}
      security:
        - CognitoAuth: []

    post:
      tags:
        - /clientes
      summary: "Cadastra um novo cliente na base de dados"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                  example: '{"nome":"NomeDoCliente", "endereco":"EnderecoDoCliente", "telefone":"TelefoneDoCliente", "email":"EmailDoCliente", "dispositivos":"DeviceDoCliente" }'
    
      responses:
        "200":
          description: "200 response"
          content:
            application/json: {}
      security:
        - CognitoAuth: []

    put:
      tags:
        - /clientes
      summary: "Atualiza os dados de um cliente na base de dados baseado em seu ID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                  example: '{"id":"idDeAlteracao", "nome":"NomeDoCliente", "endereco":"EnderecoDoCliente", "telefone":"TelefoneDoCliente", "email":"EmailDoCliente", "dispositivos":"DeviceDoCliente" }'
      responses:
        "200":
          description: "200 response"
          content:
            application/json: {}
      security:
        - CognitoAuth: []

    delete:
      tags:
        - /clientes
      summary: "Exclui um cliente na base de dados baseado em seu ID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                  example: '{"id":"idDeExclusao"}'
      responses:
        "200":
          description: "200 response"
          content:
            application/json: {}
      security:
        - CognitoAuth: []

    head:
      tags:
        - /clientes
      summary: "Verifica se a API está funcional, o Upertimerobot apenas verifica o statuscode 200, não é necessário nenhuma mensagem"
      responses:
        "200":
          description: "200 response"
          content:
            application/json: {}
      security:
        - CognitoAuth: []

  /creditos_carbono:
    get:
      tags:
        - /creditos_carbono
      summary: "Lista os créditos de carbono disponíveis para um gerador"
      parameters:
        - name: mac
          in: query
          required: false
          schema:
            type: string
          example: "89-AB-CD-EF-00-11"
      responses:
        "200":
          description: "200 response"
          content:
            application/json: {}
      security:
        - CognitoAuth: []

    put:
      tags:
        - /creditos_carbono
      summary: "Consome os créditos e gera um token único, simulando a blockchain."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                  example: '{"mac": "89-AB-CD-EF-00-11", "creditos": 0.91}'
      responses:
        "200":
          description: "200 response"
          content:
            application/json: {}
      security:
        - CognitoAuth: []

components:
  securitySchemes:
    CognitoAuth:
      type: apiKey
      name: CognitoAuth
      in: header
      x-amazon-apigateway-authtype: custom
